-- MySQL Script generated by MySQL Workbench
-- Thu Oct 13 12:48:02 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema database281
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `database281` ;

-- -----------------------------------------------------
-- Schema database281
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `database281` DEFAULT CHARACTER SET utf8 ;
-- -----------------------------------------------------
USE `database281` ;

-- -----------------------------------------------------
-- Table `database281`.`files`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `database281`.`files` ;

CREATE TABLE IF NOT EXISTS `database281`.`files` (
  `file_id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `filename` VARCHAR(45) NOT NULL,
  `user_email` VARCHAR(255) NOT NULL,
  `user_firstname` VARCHAR(255) NULL,
  `user_lastname` VARCHAR(45) NULL,
  `upload_time` TIMESTAMP NOT NULL,
  `update_time` TIMESTAMP NOT NULL,
  `description` VARCHAR(255) NULL DEFAULT NULL,
  `download_link` VARCHAR(255) NULL,
  `is_delete` TINYINT NULL DEFAULT 0,
  `version` INT NULL DEFAULT 1,
  PRIMARY KEY (`file_id`, `user_email`, `filename`));


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
